### PR TITLE
fix(DB) Disable trash/disabled/old/deprecated/unbalanced items

### PR DESCRIPTION
**Pull request by YggdrasilWotLK**
## Changes Proposed:
- Filter out wildly unbalanced items replacing almost all the seeding in certain categories (mostly engineering gadgets)
- Disable all items with names old, deprecated, tomes and other spell books no longer used in WotLK, NPC equipment, "seasonal fish" items, etc.

## Issues Addressed:

- Closes https://github.com/azerothcore/mod-ah-bot/issues/80
- Partially adresses https://github.com/azerothcore/mod-ah-bot/issues/78

## Tests Performed:

- Builds fine, tested in game

## How to Test the Changes:

1. Import SQL query
2. Re-seed AH
3. The trash/disabled/QA/etc. items are now virtually gone

### CODE REVIEW

**Comment by Helias** [comment]
the build is failing, not usre if it depends on your PR

**Comment by YggdrasilWotLK** [comment]
I'd assume it's the order in which the SQL files are loaded? My PR has a SQL script inserting rows into the table for disabled items but it's running before the table is constructed by mod_auctionhousebot.sql. Is there a particular naming scheme I ought to follow for PRs in this repo or just any name alphabetically after mod_auctionhousebot.sql?

**Comment by Helias** [comment]
> I'd assume it's the order in which the SQL files are loaded? My PR has a SQL script inserting rows into the table for disabled items but it's running before the table is constructed by mod_auctionhousebot.sql. Is there a particular naming scheme I ought to follow for PRs in this repo or just any name alphabetically after mod_auctionhousebot.sql?

I guess is alphabetical, try to rename it `z_filter...`

**Comment by Helias** [comment]
now it seems working, so the problem is the name and considering the alphabetical order, if you want to keep the current file name I can merge the PR, otherwise you could find a better name for it

**Comment by YggdrasilWotLK** [comment]
The name is perfectly fine as is!

**Comment by Helias** [comment]
ok, merged, thanks!

**Pull request merged**
