### PR TITLE
Build: Fix build in actual AC

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
##### CHANGES PROPOSED:
- Support `*-interface` library
- Fix build in actual AC

##### TESTS PERFORMED:
- [x] Build in VS 16 2019

##### KNOWN ISSUES AND TODO LIST:
- [x] Build in Linux
- [x] Test in game

### CODE REVIEW

**Comment by Viste** [comment]
https://paste2.org/mAAmDLZ1

**Comment by Winfidonarleyan** [comment]
@Viste thanks for the test

**Comment by Winfidonarleyan** [comment]
@Viste please rebuild :)

**Comment by Viste** [comment]
```
Scanning dependencies of target worldserver
[ 98%] Building CXX object src/server/worldserver/CMakeFiles/worldserver.dir/RemoteAccess/RASocket.cpp.o
[ 98%] Building CXX object src/server/worldserver/CMakeFiles/worldserver.dir/CommandLine/CliRunnable.cpp.o
[ 98%] Building CXX object src/server/worldserver/CMakeFiles/worldserver.dir/Main.cpp.o
[ 98%] Building CXX object src/server/worldserver/CMakeFiles/worldserver.dir/RemoteAccess/RARunnable.cpp.o
[100%] Building CXX object src/server/worldserver/CMakeFiles/worldserver.dir/Master.cpp.o
[100%] Building CXX object src/server/worldserver/CMakeFiles/worldserver.dir/TCSoap/TCSoap.cpp.o
[100%] Building CXX object src/server/worldserver/CMakeFiles/worldserver.dir/WorldThread/WorldRunnable.cpp.o
[100%] Linking CXX executable worldserver
[100%] Built target worldserver``` good now

**Comment by Winfidonarleyan** [comment]
Good, thanks

**Comment by milestorme** [comment]
tested debian 9 x64 working , compiles and works in game
`>AzerothCore rev. a0cb2c0b7c66+ 2019-04-13 16:09:19 +0000 (pr-5 branch) (Unix, Release)`

**Comment by Winfidonarleyan** [comment]
Thanks for testing, @milestorme

**Comment by BarbzYHOOL** [comment]
good job guys!!!

**Pull request merged**
