### PR TITLE
Fix the patch

### PR DESCRIPTION
**Pull request by BarbzYHOOL**
I didn't compile with this yet, but `git apply` worked fine

Closes https://github.com/azerothcore/mod-ah-bot/issues/8

### CODE REVIEW

**Comment by dd667** [comment]
Hi,
Compiled "AzerothCore rev. 4da4ad4e0d6e+ 2020-01-31 08:05:31 +0000 (master branch) (Win64, Release) (worldserver-daemon)" with patch applied. Compiles fine but the ahbot does not add any items to the auction house. The only thing I get in the logs is: 

```
"2020-02-01 11:23:38 AHSeller: Adding 2000 Auctions
2020-02-01 11:23:38 ERROR: AHSeller: Current Auctineer GUID is 79707
2020-02-01 11:23:38 ERROR: AHSeller: 2000 items
2020-02-01 11:23:38 ERROR: AHSeller: 1 count
2020-02-01 11:23:38 ERROR: AHSeller: 2 count
2020-02-01 11:23:38 ERROR: AHSeller: 3 count..."
``` and so on.

Hope you can make sense out of it.

**Comment by BarbzYHOOL** [comment]
I haven't tested the module yet, but I will

Also I feel like these are not errors but just warnings wrongly labelled

**Comment by TobiMiller** [comment]
i havent used your patch and created a few days earlier a new patch and i have the same problem like @dd667 that the ahbot is not selling anything

**Comment by TobiMiller** [comment]
it doesnt work but you merge? :D is that the way to go?

**Comment by BarbzYHOOL** [comment]
feel free to revert to before this PR then, it will solve all your problems and don't talk to me if it doesn't

**Comment by TobiMiller** [comment]
the patch itself works. but the rest of the mod doesnt.

**Comment by BarbzYHOOL** [comment]
Seems like you made a mistake in your patch too TobiMiller, like me

Fixed on latest commit on master now.

**Pull request merged**
