### PR TITLE
Travis fixes

### PR DESCRIPTION
**Pull request by rbedfordpro**
module should compile with travis now for testing.
updated one config, added missing value "DisabledItems" string

### CODE REVIEW

**Comment by rbedfordpro** [comment]
barbz has enabled travis for this repo (not sure if that will take effect this PR or next)

**Comment by BarbzYHOOL** [comment]
do we have to close and reopen for travis to start? don't remember

**Comment by Stoabrogga** [comment]
I removed those "REPLACE WITH if STATEMENT FOR TRAVIS COMPILE" comments, as they are not needed, and changed the code style of the if statements a bit. Travis is currently running, let's wait for the result.

**Comment by BarbzYHOOL** [comment]
All checks have passed
1 successful check

**Comment by Stoabrogga** [comment]
This looks ok to me. I did not test it, though, and won't do it as I sadly don't have the time.

**Comment by BarbzYHOOL** [comment]
did you test ingame @rbedfordpro ?

**Comment by rbedfordpro** [comment]
Yes, I have this currently running (with the changes I made) on my server. Once you set it up per the instructions in the README and make the proper config file changes (adding in the account and the character IDs) it seems to load just fine and is populating my auctionhouse with some items.

**Comment by wizzymore** [comment]
Tested and everything worked perfect!

Well done @rbedfordpro !

**Comment by milestorme** [comment]
Great job @rbedfordpro

**Pull request merged**
