### PR TITLE
Add compatibility with AH threading PR request

### PR DESCRIPTION
**Pull request by Takenbacon**
## Changes Proposed:
- Adds support for AH threading PR request (https://github.com/azerothcore/azerothcore-wotlk/pull/20830)
- Note to maintainers: do not merge until the parent AH threading PR request is first merged.

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

### CODE REVIEW

**Comment by Helias** [comment]
The pipeline reported this error
```
/home/runner/work/mod-ah-bot/mod-ah-bot/modules/mod-ah-bot/src/AuctionHouseBot.cpp:554:53: fatal error: no member named 'GetAuctionHouseEntryFromFactionTemplate' in 'AuctionHouseMgr'; did you mean 'GetAuctionHouseEntryFromHouse'?
  554 |     AuctionHouseEntry const* ahEntry = sAuctionMgr->GetAuctionHouseEntryFromFactionTemplate(config->GetAHFID());
      |                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                     GetAuctionHouseEntryFromHouse
/home/runner/work/mod-ah-bot/mod-ah-bot/src/server/game/AuctionHouse/AuctionHouseMgr.h:207:37: note: 'GetAuctionHouseEntryFromHouse' declared here
  207 |     static AuctionHouseEntry const* GetAuctionHouseEntryFromHouse(uint8 houseId);
      |                                     ^
1 error generated.
gmake[2]: *** [modules/CMakeFiles/modules.dir/build.make:93: modules/CMakeFiles/modules.dir/mod-ah-bot/src/AuctionHouseBot.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
[ 18%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Commands/cs_account.cpp.o
/home/runner/work/mod-ah-bot/mod-ah-bot/modules/mod-ah-bot/src/AuctionHouseBotAuctionHouseScript.cpp:92:13: fatal error: use of undeclared identifier 'AuctionHouseId'; did you mean 'AuctionHouses'?
   92 |         if (AuctionHouseId(ahEntry->houseId) == AuctionHouseId::Alliance)
      |             ^
/home/runner/work/mod-ah-bot/mod-ah-bot/src/server/game/AuctionHouse/AuctionHouseMgr.h:66:6: note: 'AuctionHouses' declared here
   66 | enum AuctionHouses
      |      ^
1 error generated.
gmake[2]: *** [modules/CMakeFiles/modules.dir/build.make:107: modules/CMakeFiles/modules.dir/mod-ah-bot/src/AuctionHouseBotAuctionHouseScript.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1455: modules/CMakeFiles/modules.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
```

**Comment by sudlud** [comment]
Well it won't compile anyways before the auctionhouse PR was merged in the core, right?

**Comment by Takenbacon** [comment]
> Well it won't compile anyways before the auctionhouse PR was merged in the core, right?

Lol yeah, you're right. I completely blanked that one out. It's been a long night for me! 😂

**Comment by Helias** [comment]
oh right, yep, we have to wait to merge the azerothcore-wotlk PR

**Review by Grimdhex — APPROVED** [review]

**Review by sudlud — APPROVED** [review]

**Pull request merged**
